name: forecast_bias_correction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - dask
  - dask-jobqueue
  - dask-core
  - xarray
  - numpy
  - netCDF4
  - scipy
  - pytest
  - pre-commit
  - pip
  - pip:
    - surpyval
    - formulaic
